object Versions {
    // Classpath versions
    const val gradleVersion = "7.1.2"
    const val kotlinVersion = "1.6.10"
    const val navigationVersion = "2.4.1"
    const val googleServicesVersion = "4.3.10"


    // App dependencies
    const val androidXVersion = "1.0.0"
    const val androidXAnnotations = "1.3.0"
    const val androidXLegacySupport = "1.0.0"
    const val appCompatVersion = "1.4.1"
    const val archLifecycleVersion = "2.2.0"
    const val lifecycleVersion = "2.4.1"
    const val cardVersion = "1.0.0"
    const val materialVersion = "1.5.0"
    const val fragmentVersion = "1.4.1"
    const val recyclerViewVersion = "1.2.1"
    const val mockitoVersion = "2.19.0"
    const val constraintVersion = "2.1.3"
    const val dexMakerVersion = "2.28.1"
    const val coroutinesVersion = "1.5.0"
    const val roomVersion = "2.4.2"
    const val truthVersion = "0.44"
    const val junitVersion = "4.13.2"
    const val extJUnitVersion = "1.1.3"
    const val androidXTestCoreVersion = "1.4.0"
    const val robolectricVersion = "4.7.3"
    const val androidXTestExtKotlinRunnerVersion = "1.1.3"
    const val archTestingVersion = "2.1.0"
    const val playServicesLocationVersion = "19.0.0"
    const val playServiceMapsVersion = "18.0.1"
    const val hamcrestVersion = "1.3"
    const val androidXTestRulesVersion = "1.4.0"
    const val espressoVersion = "3.4.0"
    const val gsonVersion = "2.8.6"
    const val firebaseUIAuthVersion = "8.0.0"
    const val firebaseAuthVersion = "21.0.2"
    const val playServicesAuthVersion = "20.0.0"
    const val koinVersion = "2.0.1"
}
